### ISSUE TITLE
adding jsonschema feature gives error

### ISSUE THREAD

**Issue by philvarner** [gadomski/stac-rs#109]
Adding the jsonschema option per the docs:

```
stac = { version = "0.1", features = ["jsonschema"]}
```

and building gives the error:

```
the package `foobar` depends on `stac`, with features: `jsonschema` but `stac` does not have these features.
```

**Comment by gadomski** [comment]
Ah, I haven't released `jsonschema` support yet. Try this:

```toml
[dependencies]
stac = { git = "https://github.com/gadomski/stac-rs", features = ["jsonschema"] }
```

I'll either update the README or release `jsonchema` to fix, thanks for pointing that out.
